import pandas as pd
df = pd.read_csv(r"C:\Users\badri\OneDrive\Desktop\Data Science\Python Codes\Diabetes data.txt")
# print(df.head())
# print(df.tail())
# print("Length of DF is", (len(df)))
# print(type(df))
# print("Columns are:", df.columns)
# print(df.info())
# print(df.describe())
# print(df['Pregnancies'])
# print(df.isna().any())
# print(df.isna().sum())
# print(df.dtypes)
# print(df.head())
# print(df.set_index('Outcome'))
# print(df.head())
# # print(df.index)
# f = open(r"C:\Users\badri\OneDrive\Desktop\Prof.txt")
# print(f.read())
print(df.columns)
print(df['SkinThickness'].value_counts()) 
print(df.head(3))
print(df.iloc[0:2,0:4])
df2 = df[(df['Outcome']== 1) &(df['Age'] > 52)]
print(len(df2))